### ISSUE TITLE
Access denied on OS X

### ISSUE THREAD

**Issue by cbare** [itdaniher/WeDoMore#6]
Hi, cool project. Is this know to work (or not) on Mac OS X? I tried and got the following error:

```python
import logging
from wedo import WeDo
logging.basicConfig()
wd = WeDo()
wd.motor_a = 100
```

```
ERROR:wedo:Could not write to driver
Traceback (most recent call last):
  File "wedo/__init__.py", line 109, in setMotors
    self.dev.ctrl_transfer(bmRequestType=0x21, bRequest=0x09, wValue=0x0200, wIndex=0, data_or_wLength=data)
  File "build/bdist.macosx-10.9-x86_64/egg/usb/core.py", line 962, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "build/bdist.macosx-10.9-x86_64/egg/usb/core.py", line 146, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "build/bdist.macosx-10.9-x86_64/egg/usb/backend/libusb1.py", line 747, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "build/bdist.macosx-10.9-x86_64/egg/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 13] Access denied (insufficient permissions)
```

I came across a [ticket for libusb](http://www.libusb.org/ticket/89) that seems to indicate that Mac OS X is not supported. Any hints appreciated.

**Comment by itdaniher** [comment]
Would you try running python with sudo?

**Comment by cbare** [comment]
OK, I got the same thing:

```
$ sudo python
Password:
Python 2.7.8 (default, Oct 19 2014, 16:03:53) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> from wedo import WeDo
>>> 
>>> logging.basicConfig()
>>> 
>>> wd = WeDo()
>>> wd.motor_a = 100
ERROR:wedo:Could not write to driver
Traceback (most recent call last):
  File "wedo/__init__.py", line 109, in setMotors
    self.dev.ctrl_transfer(bmRequestType=0x21, bRequest=0x09, wValue=0x0200, wIndex=0, data_or_wLength=data)
  File "build/bdist.macosx-10.9-x86_64/egg/usb/core.py", line 962, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "build/bdist.macosx-10.9-x86_64/egg/usb/core.py", line 146, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "build/bdist.macosx-10.9-x86_64/egg/usb/backend/libusb1.py", line 747, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "build/bdist.macosx-10.9-x86_64/egg/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 13] Access denied (insufficient permissions)
```

**Comment by itdaniher** [comment]
OSX is supported by libusb. It's been a year or two since I last tried pyusb on OSX.

It's possible another driver could be using the device. Poke around in osx's device manager, see if you can find the wedo, and moreover see if there's any software indicated as currently handling the device?

**Comment by cbare** [comment]
The device manager sees it. Under *USB-3.0 Hi-Speed Bus* it says:
```
LEGO USB Hub V1.00:

  Product ID:	0x0003
  Vendor ID:	0x0694  (Lego Group)
  Version:	 1.00
  Speed:	Up to 1.5 Mb/sec
  Location ID:	0x14200000 / 2
  Current Available (mA):	500
  Current Required (mA):	100
```
I don't see anything about drivers.

Thanks for the response, BTW.

**Comment by cbare** [comment]
I did a bit more poking around and it seems that the wedo device identifies itself as a "USB Human Interface Device" device and it sounds like OS-X's built in HID driver binds to the device and I'm seeing the permission error because libusb is trying to bind to it when there's already a driver bound. (...with the caveat that my understanding is pretty shaky on all this.)

Scratch can talk to it via a non-open-source browser plugin.

**Comment by itdaniher** [comment]
Iiiinteresting.

That sounds plausible. I know Windows has trouble unbinding kernel drivers from inside Python.

Link me to the browser plugin?

**Comment by cbare** [comment]
Info on the scratch extension is [here](http://wiki.scratch.mit.edu/wiki/LEGO_Education_WeDo_Robotics_Kit) along with [installation instructsions](https://scratch.mit.edu/scratchr2/static/ext/download.html). But, it's distributed as a closed source binary. Bummer!

**Comment by Stanowczo** [comment]
Hi there! I am aware of the age of this issue, but maybe someone other than me is still interested in using this old WeDo 1.0. I just managed to make it work with pyusb 1.3.1 using libusb as backend (installed with homebew) on MacOS 26 and on Python 3.12.6. Sudo privileges were needed, I plan to find a way to run it without sudo.
