### ISSUE TITLE
Package is Broken

### ISSUE THREAD

**Issue by crlane** [itdaniher/WeDoMore#9]
Tried on Linux and Mac in fresh virtualenv. Received similar error on both:

```
You are using pip version 6.0.3, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting wedo
  Downloading wedo-1.0.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/45/h_fcdsz55hd720g6kz4nl5180000gn/T/pip-build-w2sQSU/wedo/setup.py", line 20, in <module>
        long_description=''.join([read('README.rst'), '\n\n', read('CHANGES.rst')]),
      File "/var/folders/45/h_fcdsz55hd720g6kz4nl5180000gn/T/pip-build-w2sQSU/wedo/setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/var/folders/45/h_fcdsz55hd720g6kz4nl5180000gn/T/pip-build-w2sQSU/wedo/CHANGES.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/var/folders/45/h_fcdsz55hd720g6kz4nl5180000gn/T/pip-build-w2sQSU/wedo/setup.py", line 20, in <module>

        long_description=''.join([read('README.rst'), '\n\n', read('CHANGES.rst')]),

      File "/var/folders/45/h_fcdsz55hd720g6kz4nl5180000gn/T/pip-build-w2sQSU/wedo/setup.py", line 8, in read

        return open(os.path.join(os.path.dirname(__file__), fname)).read()

    IOError: [Errno 2] No such file or directory: '/var/folders/45/h_fcdsz55hd720g6kz4nl5180000gn/T/pip-build-w2sQSU/wedo/CHANGES.rst'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/45/h_fcdsz55hd720g6kz4nl5180000gn/T/pip-build-w2sQSU/wedo
```

**Comment by itdaniher** [comment]
I'm not sure what package is currently being used by PyPi, or, in fact, how 'wedo' resolves to this project, but "pip install https://github.com/itdaniher/WeDoMore/archive/master.zip" should work for you.

Regards,
Ian

**Comment by crlane** [comment]
@itdaniher Yes, I was able to install with pip from local source also, just doesn't work with the packaged version.

**Comment by gbin** [comment]
The package has been bumped, sorry it took so long !

**Comment by a-nanasov** [comment]
@gbin, the package at pypi is still missing the CHANGES.rst file, would you mind fixing this please?

**Comment by KTibow** [comment]
@gbin Still getting this error... Any plans?
